workshops:
  list:
    - id: 1
      name: Manchester
      address: 14 Bury New Rd, Manchester
      vehicleTypes:
        - Car
        - Truck
      url: http://192.168.1.2:9004
      apiPrefix: /api/v2
      paths:
        getSlots: 
          path: /tire-change-times?from={from}&page={page}&amount={amount}
          method: GET
        bookSlot: 
          path: /tire-change-times/{id}/booking
          method: POST
      contentType: application/json
    - id: 2
      name: London
      address: 1A Gunton Rd, London
      vehicleTypes:
        - Car
      url: http://192.168.1.2:9003
      apiPrefix: /api/v1
      paths:
        getSlots: 
          path: /tire-change-times/available?from={from}&until={to}
          method: GET
        bookSlot: 
          path: /tire-change-times/{id}/booking
          method: PUT
          dynamicRootName: london.tireChangeBookingRequest
      contentType: text/xml
